version: "3"
services: 
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-springboot:7.0
    # container_name: "backend"
    volumes: 
    - ./my-note/entrypoint.sh:/entrypoint.sh
    entrypoint: 
    - /entrypoint.sh
    depends_on: 
    - myes
    - mymysql
    - myredis
    ports:
    - 5005:5005
    - 8082:8082
    privileged: true
    #network_mode: host
  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-vue:5.0   
    volumes:
    - ./vue-project/entrypoint.sh:/entrypoint.sh
    entrypoint: 
    - /entrypoint.sh
    ports: 
    - 5000:5000
    depends_on: 
    - backend
      #network_mode: host
  mymysql:
    image: mysql
    # container_name: mymysql
    volumes: 
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    # ./mysql/data:/var/lib/mysql
    environment: 
    - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    #network_mode: host
  myes:
    privileged: true
    image: elasticsearch:6.8.6
    # container_name: myes
    volumes: 
    - ./elasticsearch/ik/:/usr/share/elasticsearch/plugins/ik/
    # - ./elasticsearch/data:/usr/share/elasticsearch/data
    # - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #network_mode: host
  myredis:
    image: redis
    # container_name: myredis
    #network_mode: host
    #deploy:
    #  replicas: 3
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"
  myzookeeper:
    image: zookeeper
    #network_mode: host
  mykafka:
    image: wurstmeister/kafka
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=myzookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=mykafka
    depends_on:
    - myzookeeper
  jobmanager:
    image: flink:1.10.0
    ports:
    - 8081:8081
    command: jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
        # network_mode: host
    volumes:
    - ./flink/login-detection.jar:/login-detection.jar
    - ./flink/note-statistics.jar:/note-statistics.jar
    - ./flink/conf/sql-client-defaults.yaml:/opt/flink/conf/sql-client-defaults.yaml
    - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    - ./flink/flink-json.jar:/opt/flink/lib/flink-json.jar
    - ./flink/flink-jdbc.jar:/opt/flink/lib/flink-jdbc.jar
    - ./flink/flink-mysql.jar:/opt/flink/lib/flink-mysql.jar
    - ./flink/my-flink-kafka.jar:/opt/flink/lib/my-flink-kafka.jar
    - ./flink/flink-csv.jar:/opt/flink/lib/flink-csv.jar
    # - D:/Temp7/flink-blink.jar:/opt/flink/lib/flink-blink.jar
      #- D:/Temp7/flink-cep.jar:/opt/flink/lib/flink-cep.jar
  taskmanager:
    image: flink:1.10.0
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    #network_mode: host
    volumes:
    - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    - ./flink/conf/sql-client-defaults.yaml:/opt/flink/conf/sql-client-defaults.yaml
    - ./flink/flink-json.jar:/opt/flink/lib/flink-json.jar
    - ./flink/flink-jdbc.jar:/opt/flink/lib/flink-jdbc.jar
    - ./flink/flink-mysql.jar:/opt/flink/lib/flink-mysql.jar
    - ./flink/my-flink-kafka.jar:/opt/flink/lib/my-flink-kafka.jar
    - ./flink/flink-csv.jar:/opt/flink/lib/flink-csv.jar
    - ./flink/flink-cep.jar:/opt/flink/lib/flink-cep.jar
    # - D:/Temp7/flink-blink.jar:/opt/flink/lib/flink-blink.jar
