version: "3"
services: 
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-springboot:7.0
    container_name: "backend"
    volumes: 
    - ./my-note/project/:/project/
    - ./my-note/entrypoint.sh:/entrypoint.sh
    - ./my-note/settings.xml:/usr/share/maven/conf/settings.xml
    - ./my-note/a.jar:/a.jar
    entrypoint: 
    - /entrypoint.sh
    depends_on: 
    - myes
    - mymysql
    - myredis
    ports:
    - 5005:5005
    - 8082:8082
    #network_mode: host
  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/cookie0512/note-vue:5.0   
    volumes:
    - ./vue-project/entrypoint.sh:/entrypoint.sh
    entrypoint: 
    - /entrypoint.sh
    ports: 
    - 5000:5000
    depends_on: 
    - backend
      #network_mode: host
  mymysql:
    image: mysql
    container_name: mymysql
    volumes: 
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    # ./mysql/data:/var/lib/mysql
    environment: 
    - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    #network_mode: host
  myes:
    image: elasticsearch:6.8.6
    container_name: myes
    volumes: 
    - ./elasticsearch/ik/:/usr/share/elasticsearch/plugins/ik/
    # - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #network_mode: host
  myredis:
    image: redis
    container_name: myredis
    #network_mode: host
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"
  myzookeeper:
    image: zookeeper
    #network_mode: host
  mykafka:
    image: wurstmeister/kafka
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=myzookeeper:2181
    - KAFKA_ADVERTISED_HOST_NAME=mykafka
    depends_on:
    - myzookeeper
  jobmanager:
    image: flink
    ports:
    - 8081:8081
    command: jobmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
        # network_mode: host
    volumes:
    - ./flink/login-detection.jar:/login-detection.jar
    - ./flink/note-statistics.jar:/note-statistics.jar
  taskmanager:
    image: flink
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    #network_mode: host
